//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsynControllers_Prj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcpetionLogDb
    {
        public long Logid { get; set; }
        public string ExceptionMsg { get; set; }
        public string ExceptionType { get; set; }
        public string ExceptionSource { get; set; }
        public string ExceptionUrl { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
    }
}
