//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsynControllers_Prj.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InfiniteDBEntities1 : DbContext
    {
        public InfiniteDBEntities1()
            : base("name=InfiniteDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dept> Depts { get; set; }
        public virtual DbSet<Emp> Emps { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductSale> ProductSales { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<tblDepartment> tblDepartments { get; set; }
        public virtual DbSet<tblEmployee> tblEmployees { get; set; }
        public virtual DbSet<cityData> cityDatas { get; set; }
        public virtual DbSet<empdata> empdatas { get; set; }
        public virtual DbSet<ExcpetionLogDb> ExcpetionLogDbs { get; set; }
        public virtual DbSet<Stable1> Stable1 { get; set; }
        public virtual DbSet<Stable2> Stable2 { get; set; }
    
        [DbFunction("InfiniteDBEntities1", "fn_getAllEmpData")]
        public virtual IQueryable<fn_getAllEmpData_Result> fn_getAllEmpData(Nullable<int> did)
        {
            var didParameter = did.HasValue ?
                new ObjectParameter("did", did) :
                new ObjectParameter("did", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_getAllEmpData_Result>("[InfiniteDBEntities1].[fn_getAllEmpData](@did)", didParameter);
        }
    
        [DbFunction("InfiniteDBEntities1", "fn_GetEmpByGender")]
        public virtual IQueryable<fn_GetEmpByGender_Result> fn_GetEmpByGender(string gen)
        {
            var genParameter = gen != null ?
                new ObjectParameter("gen", gen) :
                new ObjectParameter("gen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_GetEmpByGender_Result>("[InfiniteDBEntities1].[fn_GetEmpByGender](@gen)", genParameter);
        }
    
        public virtual int ExceptionLoggingintoDB(string exceptionmsg, string exceptiontype, string exceptionsource, string exceptionurl)
        {
            var exceptionmsgParameter = exceptionmsg != null ?
                new ObjectParameter("exceptionmsg", exceptionmsg) :
                new ObjectParameter("exceptionmsg", typeof(string));
    
            var exceptiontypeParameter = exceptiontype != null ?
                new ObjectParameter("exceptiontype", exceptiontype) :
                new ObjectParameter("exceptiontype", typeof(string));
    
            var exceptionsourceParameter = exceptionsource != null ?
                new ObjectParameter("exceptionsource", exceptionsource) :
                new ObjectParameter("exceptionsource", typeof(string));
    
            var exceptionurlParameter = exceptionurl != null ?
                new ObjectParameter("exceptionurl", exceptionurl) :
                new ObjectParameter("exceptionurl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ExceptionLoggingintoDB", exceptionmsgParameter, exceptiontypeParameter, exceptionsourceParameter, exceptionurlParameter);
        }
    
        public virtual ObjectResult<sp_addEmployee_Result> sp_addEmployee(Nullable<int> eid, string ename, string gen, Nullable<decimal> sal, Nullable<int> did)
        {
            var eidParameter = eid.HasValue ?
                new ObjectParameter("eid", eid) :
                new ObjectParameter("eid", typeof(int));
    
            var enameParameter = ename != null ?
                new ObjectParameter("ename", ename) :
                new ObjectParameter("ename", typeof(string));
    
            var genParameter = gen != null ?
                new ObjectParameter("gen", gen) :
                new ObjectParameter("gen", typeof(string));
    
            var salParameter = sal.HasValue ?
                new ObjectParameter("sal", sal) :
                new ObjectParameter("sal", typeof(decimal));
    
            var didParameter = did.HasValue ?
                new ObjectParameter("did", did) :
                new ObjectParameter("did", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_addEmployee_Result>("sp_addEmployee", eidParameter, enameParameter, genParameter, salParameter, didParameter);
        }
    
        public virtual ObjectResult<sp_empdetails_Result> sp_empdetails(Nullable<int> did, Nullable<decimal> sal)
        {
            var didParameter = did.HasValue ?
                new ObjectParameter("did", did) :
                new ObjectParameter("did", typeof(int));
    
            var salParameter = sal.HasValue ?
                new ObjectParameter("sal", sal) :
                new ObjectParameter("sal", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_empdetails_Result>("sp_empdetails", didParameter, salParameter);
        }
    
        public virtual ObjectResult<sp_employeedata_Result> sp_employeedata()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_employeedata_Result>("sp_employeedata");
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_errorhandler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_errorhandler");
        }
    
        public virtual int sp_getdept(Nullable<int> eid)
        {
            var eidParameter = eid.HasValue ?
                new ObjectParameter("eid", eid) :
                new ObjectParameter("eid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getdept", eidParameter);
        }
    
        public virtual int sp_getempCount(Nullable<int> deptid, ObjectParameter totsal)
        {
            var deptidParameter = deptid.HasValue ?
                new ObjectParameter("deptid", deptid) :
                new ObjectParameter("deptid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getempCount", deptidParameter, totsal);
        }
    
        public virtual int sp_getEmpSalary(string empname, ObjectParameter esal)
        {
            var empnameParameter = empname != null ?
                new ObjectParameter("empname", empname) :
                new ObjectParameter("empname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getEmpSalary", empnameParameter, esal);
        }
    
        public virtual ObjectResult<sp_getSalary_Result> sp_getSalary(Nullable<int> eid)
        {
            var eidParameter = eid.HasValue ?
                new ObjectParameter("eid", eid) :
                new ObjectParameter("eid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getSalary_Result>("sp_getSalary", eidParameter);
        }
    
        public virtual ObjectResult<string> sp_greetings()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_greetings");
        }
    
        public virtual int Sp_ProductSalesMade(Nullable<int> prdid, Nullable<int> qty_tosell)
        {
            var prdidParameter = prdid.HasValue ?
                new ObjectParameter("prdid", prdid) :
                new ObjectParameter("prdid", typeof(int));
    
            var qty_tosellParameter = qty_tosell.HasValue ?
                new ObjectParameter("qty_tosell", qty_tosell) :
                new ObjectParameter("qty_tosell", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_ProductSalesMade", prdidParameter, qty_tosellParameter);
        }
    
        public virtual ObjectResult<sp_sample_Result> sp_sample()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_sample_Result>("sp_sample");
        }
    
        public virtual int sp_TaxCalculator(Nullable<int> eid, ObjectParameter annualsal)
        {
            var eidParameter = eid.HasValue ?
                new ObjectParameter("eid", eid) :
                new ObjectParameter("eid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TaxCalculator", eidParameter, annualsal);
        }
    
        public virtual ObjectResult<string> sp_Welcome(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_Welcome", nameParameter);
        }
    }
}
