//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsynControllers_Prj.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tblEmployee
    {
        [DisplayName("Employee Number")]
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public string Gender { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<int> DepartmentId { get; set; }
    
        public virtual tblDepartment tblDepartment { get; set; }
    }
}
